### ISSUE TITLE
websocket问题

### ISSUE THREAD

**Issue by rookbird** [Cyaim/WebSocketServer#9]
你好，我在wpf中使用，但是没有具体的文档，可以给出不使用startup注册的方式文档么，谢谢大佬

**Comment by Cyaim** [comment]
WebSocketServer依赖于Kestral的WebSocket模块，需要先在WPF中初始化WebHost才行

**Comment by Cyaim** [comment]
WebSocketServer依赖于Kestral的WebSocket模块，先在WPF中初始化WebHost就行

**Comment by Cyaim** [comment]
![image](https://github.com/user-attachments/assets/4f7fb8fe-c1ef-4214-9dc9-b83b700a287c)
Cyaim.WebSocketServer.Example.Wpf实现效果如图

**Comment by Cyaim** [comment]
若没有问题这个issue就关闭了，后面有问题可以再次打开
